// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa0wfPJOKXOrSV1jm4qpnr-vWNEeGkcXY',
    appId: '1:920907309027:web:d51174a101e4fcd94c8ad6',
    messagingSenderId: '920907309027',
    projectId: 'meetmatedb',
    authDomain: 'meetmatedb.firebaseapp.com',
    storageBucket: 'meetmatedb.appspot.com',
    measurementId: 'G-PHQG3T8DF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSw4njnmsskloc4tYjg31A2QBEFPymewk',
    appId: '1:920907309027:android:5903355fa129502a4c8ad6',
    messagingSenderId: '920907309027',
    projectId: 'meetmatedb',
    storageBucket: 'meetmatedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_8_9I6_hDqu4E3rpXp3NX3mw-1aq7dI',
    appId: '1:920907309027:ios:3a3025b49cec3a244c8ad6',
    messagingSenderId: '920907309027',
    projectId: 'meetmatedb',
    storageBucket: 'meetmatedb.appspot.com',
    iosBundleId: 'com.example.meetMate',
  );
}
